"""init tables

Revision ID: 0821cea33721
Revises: 
Create Date: 2025-10-27 00:53:28.789033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0821cea33721'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.drop_index(op.f('idx_session_user_id'), table_name='session')
    op.drop_table('session')
    op.alter_column('app_users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('app_users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('app_users', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_app_users_created_at'), table_name='app_users')
    op.drop_index(op.f('idx_app_users_email'), table_name='app_users')
    op.add_column('device_tokens', sa.Column('token', sa.String(), nullable=False))
    op.add_column('device_tokens', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('device_tokens', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('device_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('device_tokens', 'platform',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_device_tokens_token'), table_name='device_tokens')
    op.drop_index(op.f('idx_device_tokens_user_id'), table_name='device_tokens')
    op.create_unique_constraint(None, 'device_tokens', ['token'])
    op.drop_column('device_tokens', 'token_t')
    op.drop_column('device_tokens', 'last_used_at')
    op.add_column('item_option_groups', sa.Column('name', sa.String(), nullable=True))
    op.drop_index(op.f('idx_item_option_groups_menu_item_id'), table_name='item_option_groups')
    op.drop_column('item_option_groups', 'group_name')
    op.add_column('item_options', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('item_options', 'price_delta',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('idx_item_options_group_id'), table_name='item_options')
    op.drop_index(op.f('idx_item_options_is_available'), table_name='item_options')
    op.drop_column('item_options', 'option_name')
    op.alter_column('menu_items', 'shop_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('menu_items', 'item_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_index(op.f('idx_menu_items_is_active'), table_name='menu_items')
    op.drop_index(op.f('idx_menu_items_shop_id'), table_name='menu_items')
    op.drop_constraint(op.f('menu_items_shop_id_fkey'), 'menu_items', type_='foreignkey')
    op.alter_column('order_item_options', 'name_snapshot',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('order_item_options', 'price_delta',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('idx_order_item_options_item_id'), table_name='order_item_options')
    op.drop_index(op.f('idx_order_item_options_option_id'), table_name='order_item_options')
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('order_items', 'line_total',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('idx_order_items_order_id'), table_name='order_items')
    op.add_column('orders', sa.Column('note_text', sa.String(), nullable=True))
    op.alter_column('orders', 'shop_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('orders', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_orders_created_at'), table_name='orders')
    op.drop_index(op.f('idx_orders_shop_id'), table_name='orders')
    op.drop_index(op.f('idx_orders_slot_id'), table_name='orders')
    op.drop_index(op.f('idx_orders_status'), table_name='orders')
    op.drop_index(op.f('idx_orders_user_id'), table_name='orders')
    op.drop_constraint(op.f('orders_shop_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_slot_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'app_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('orders', 'note')
    op.alter_column('owner_accounts', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('owner_accounts', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_index(op.f('idx_owner_accounts_email'), table_name='owner_accounts')
    op.alter_column('owner_shops', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('owner_shops', 'shop_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_owner_shops_owner_id'), table_name='owner_shops')
    op.drop_index(op.f('idx_owner_shops_shop_id'), table_name='owner_shops')
    op.create_unique_constraint('uq_owner_shop', 'owner_shops', ['owner_id', 'shop_id'])
    op.drop_constraint(op.f('owner_shops_owner_id_fkey'), 'owner_shops', type_='foreignkey')
    op.create_foreign_key(None, 'owner_shops', 'shop_accounts', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('payments', 'method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('payments', 'provider_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('payments', 'extra',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_payments_created_at'), table_name='payments')
    op.drop_index(op.f('idx_payments_order_id'), table_name='payments')
    op.drop_index(op.f('idx_payments_status'), table_name='payments')
    op.alter_column('shop_accounts', 'shop_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('shop_accounts', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('shop_accounts', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_index(op.f('idx_shop_accounts_shop_id'), table_name='shop_accounts')
    op.drop_index(op.f('idx_shop_accounts_username'), table_name='shop_accounts')
    op.drop_constraint(op.f('shop_accounts_shop_id_fkey'), 'shop_accounts', type_='foreignkey')
    op.add_column('shop_device_tokens', sa.Column('token', sa.String(), nullable=False))
    op.add_column('shop_device_tokens', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('shop_device_tokens', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('shop_device_tokens', 'shop_account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('shop_device_tokens', 'platform',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_shop_device_tokens_account_id'), table_name='shop_device_tokens')
    op.drop_index(op.f('idx_shop_device_tokens_token'), table_name='shop_device_tokens')
    op.create_unique_constraint(None, 'shop_device_tokens', ['token'])
    op.drop_column('shop_device_tokens', 'token_t')
    op.drop_column('shop_device_tokens', 'last_used_at')
    op.alter_column('shops', 'shop_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('shops', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('shops', 'tz',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('shops', 'open_hours',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_shops_created_at'), table_name='shops')
    op.drop_index(op.f('idx_shops_is_active'), table_name='shops')
    op.drop_index(op.f('idx_slot_holds_order_id'), table_name='slot_holds')
    op.drop_index(op.f('idx_slot_holds_slot_id'), table_name='slot_holds')
    op.add_column('time_slots', sa.Column('start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('time_slots', sa.Column('end', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('time_slots', 'shop_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_time_slots_active'), table_name='time_slots')
    op.drop_index(op.f('idx_time_slots_shop_id'), table_name='time_slots')
    op.drop_index(op.f('idx_time_slots_start_end'), table_name='time_slots')
    op.drop_column('time_slots', 'start_at')
    op.drop_column('time_slots', 'end_at')
    op.add_column('user_favorites', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('user_favorites', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_favorites', 'shop_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_user_favorites_shop_id'), table_name='user_favorites')
    op.drop_index(op.f('idx_user_favorites_user_id'), table_name='user_favorites')
    op.create_unique_constraint('uq_user_shop_favorite', 'user_favorites', ['user_id', 'shop_id'])
    op.drop_constraint(op.f('user_favorites_shop_id_fkey'), 'user_favorites', type_='foreignkey')
    op.create_foreign_key(None, 'user_favorites', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_favorites', 'added_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_favorites', sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.create_foreign_key(op.f('user_favorites_shop_id_fkey'), 'user_favorites', 'shops', ['shop_id'], ['id'])
    op.drop_constraint('uq_user_shop_favorite', 'user_favorites', type_='unique')
    op.create_index(op.f('idx_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_favorites_shop_id'), 'user_favorites', ['shop_id'], unique=False)
    op.alter_column('user_favorites', 'shop_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_favorites', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('user_favorites', 'created_at')
    op.add_column('time_slots', sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('time_slots', sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_time_slots_start_end'), 'time_slots', ['start_at', 'end_at'], unique=False)
    op.create_index(op.f('idx_time_slots_shop_id'), 'time_slots', ['shop_id'], unique=False)
    op.create_index(op.f('idx_time_slots_active'), 'time_slots', ['is_active'], unique=False)
    op.alter_column('time_slots', 'shop_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('time_slots', 'end')
    op.drop_column('time_slots', 'start')
    op.create_index(op.f('idx_slot_holds_slot_id'), 'slot_holds', ['slot_id'], unique=False)
    op.create_index(op.f('idx_slot_holds_order_id'), 'slot_holds', ['order_id'], unique=False)
    op.create_index(op.f('idx_shops_is_active'), 'shops', ['is_active'], unique=False)
    op.create_index(op.f('idx_shops_created_at'), 'shops', ['created_at'], unique=False)
    op.alter_column('shops', 'open_hours',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shops', 'tz',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('shops', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('shops', 'shop_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('shop_device_tokens', sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('shop_device_tokens', sa.Column('token_t', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shop_device_tokens', type_='unique')
    op.create_index(op.f('idx_shop_device_tokens_token'), 'shop_device_tokens', ['token_t'], unique=False)
    op.create_index(op.f('idx_shop_device_tokens_account_id'), 'shop_device_tokens', ['shop_account_id'], unique=False)
    op.alter_column('shop_device_tokens', 'platform',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('shop_device_tokens', 'shop_account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('shop_device_tokens', 'created_at')
    op.drop_column('shop_device_tokens', 'is_active')
    op.drop_column('shop_device_tokens', 'token')
    op.create_foreign_key(op.f('shop_accounts_shop_id_fkey'), 'shop_accounts', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_shop_accounts_username'), 'shop_accounts', ['username'], unique=False)
    op.create_index(op.f('idx_shop_accounts_shop_id'), 'shop_accounts', ['shop_id'], unique=False)
    op.alter_column('shop_accounts', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('shop_accounts', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('shop_accounts', 'shop_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('idx_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('idx_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.alter_column('payments', 'extra',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('payments', 'provider_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'owner_shops', type_='foreignkey')
    op.create_foreign_key(op.f('owner_shops_owner_id_fkey'), 'owner_shops', 'owner_accounts', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_owner_shop', 'owner_shops', type_='unique')
    op.create_index(op.f('idx_owner_shops_shop_id'), 'owner_shops', ['shop_id'], unique=False)
    op.create_index(op.f('idx_owner_shops_owner_id'), 'owner_shops', ['owner_id'], unique=False)
    op.alter_column('owner_shops', 'shop_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('owner_shops', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_owner_accounts_email'), 'owner_accounts', ['email'], unique=False)
    op.alter_column('owner_accounts', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('owner_accounts', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('orders', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'app_users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('orders_slot_id_fkey'), 'orders', 'time_slots', ['slot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('orders_shop_id_fkey'), 'orders', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('idx_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('idx_orders_slot_id'), 'orders', ['slot_id'], unique=False)
    op.create_index(op.f('idx_orders_shop_id'), 'orders', ['shop_id'], unique=False)
    op.create_index(op.f('idx_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.alter_column('orders', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('orders', 'shop_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('orders', 'note_text')
    op.create_index(op.f('idx_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.alter_column('order_items', 'line_total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.create_index(op.f('idx_order_item_options_option_id'), 'order_item_options', ['option_id'], unique=False)
    op.create_index(op.f('idx_order_item_options_item_id'), 'order_item_options', ['order_item_id'], unique=False)
    op.alter_column('order_item_options', 'price_delta',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('order_item_options', 'name_snapshot',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(op.f('menu_items_shop_id_fkey'), 'menu_items', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_menu_items_shop_id'), 'menu_items', ['shop_id'], unique=False)
    op.create_index(op.f('idx_menu_items_is_active'), 'menu_items', ['is_active'], unique=False)
    op.alter_column('menu_items', 'item_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('menu_items', 'shop_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('item_options', sa.Column('option_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_item_options_is_available'), 'item_options', ['is_available'], unique=False)
    op.create_index(op.f('idx_item_options_group_id'), 'item_options', ['group_id'], unique=False)
    op.alter_column('item_options', 'price_delta',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_column('item_options', 'name')
    op.add_column('item_option_groups', sa.Column('group_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_item_option_groups_menu_item_id'), 'item_option_groups', ['menu_item_id'], unique=False)
    op.drop_column('item_option_groups', 'name')
    op.add_column('device_tokens', sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('device_tokens', sa.Column('token_t', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'device_tokens', type_='unique')
    op.create_index(op.f('idx_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_device_tokens_token'), 'device_tokens', ['token_t'], unique=False)
    op.alter_column('device_tokens', 'platform',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('device_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('device_tokens', 'created_at')
    op.drop_column('device_tokens', 'is_active')
    op.drop_column('device_tokens', 'token')
    op.create_index(op.f('idx_app_users_email'), 'app_users', ['email'], unique=False)
    op.create_index(op.f('idx_app_users_created_at'), 'app_users', ['created_at'], unique=False)
    op.alter_column('app_users', 'display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('app_users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('app_users', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('session',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name=op.f('session_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('session_pkey'))
    )
    op.create_index(op.f('idx_session_user_id'), 'session', ['user_id'], unique=False)
    op.drop_table('sessions')
    # ### end Alembic commands ###
