"""add user_id to payments

Revision ID: a2098d1b89c5
Revises: 0821cea33721
Create Date: 2025-10-27 01:20:11.718251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2098d1b89c5'
down_revision: Union[str, Sequence[str], None] = '0821cea33721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'payments', 'app_users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###
