"""add order-time_slot relation

Revision ID: b6df0ba18af5
Revises: a2098d1b89c5
Create Date: 2025-10-27 13:41:23.130723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6df0ba18af5'
down_revision: Union[str, Sequence[str], None] = 'a2098d1b89c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'menu_items', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('time_slot_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'time_slots', ['time_slot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shop_accounts', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_accounts', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'time_slot_id')
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    # ### end Alembic commands ###
